# 11 product modules
add_subdirectory(01_calibration)
add_subdirectory(02_scanning)
add_subdirectory(03_rendering)
add_subdirectory(04_postprocessing)
add_subdirectory(Editing)
add_subdirectory(DataManager)
add_subdirectory(PipelineManager)
add_subdirectory(DeviceManager)
add_subdirectory(OperatorLib)
add_subdirectory(Observability)
add_subdirectory(11_deploy)
